### PR TITLE
Restore works.

### PR DESCRIPTION
**Pull request by nmoller**
Hi Fernando,
We needed the restore for your plugin. I coded it and I thought you could appreciate the contrib.

We met at Montreal's moot (we were sitting together the last day with the UM team). I'm currently working at UQAM and we use a lot your side_bar. 

Thanks.

Nelson

### CODE REVIEW

**Comment by ned-code** [comment]
That's very kind of you, Nelson. Much appreciated.

I owe u a beer at the next Moot!

Cheers,
Fernando

**Comment by nmoller** [comment]
The beer idea, it's a great one Fernando. But I think it's me who owes you a beer, I was glad to hear that you are the maintainer of this block. 
Have a nice day,

Nelson

**Comment by nmoller** [comment]
Hi Fernando,
I apologize for bothering you but I would like to know if you have a date for the integration in the mainstream of the plugin (If you rejected due to some policy or errors or.... please, dont hesitate to demand what it takes to facilitate your integration task).

Thanks, have a nice day.

**Comment by ned-code** [comment]
Hi Nelson, We are currently updating a batch of plugins, which we hope to release in the next few weeks. The sidebar block is a part of this batch. Thanks.

**Comment by nmoller** [comment]
I've seen. Thanks Fernando. Keep on doing that good job.

**Pull request merged**
